/**
 * @description home action types
 */
 export const REQUEST_USER_BOOK_NOW = "REQUEST_USER_BOOK_NOW";
 export const RECEIVE_USER_BOOK_NOW = "RECEIVE_USER_BOOK_NOW";
 export const FAILURE_USER_BOOK_NOW = "FAILURE_USER_BOOK_NOW";
 export const REQUEST_CLIENT_SECRET = "REQUEST_CLIENT_SECRET";
 export const RECEIVE_CLIENT_SECRET = "RECEIVE_CLIENT_SECRET";
 export const FAILURE_CLIENT_SECRET = "FAILURE_CLIENT_SECRET";