/**
 * @description home action types
 */
export const REQUEST_USER_BOOK_NOW = "REQUEST_USER_BOOK_NOW";
export const RECEIVE_USER_BOOK_NOW = "RECEIVE_USER_BOOK_NOW";
export const FAILURE_USER_BOOK_NOW = "FAILURE_USER_BOOK_NOW";
export const REQUEST_BOOKED_SLOTS = "REQUEST_BOOKED_SLOTS";
export const RECEIVE_BOOKED_SLOTS = "RECEIVE_BOOKED_SLOTS";
export const FAILURE_BOOKED_SLOTS = "FAILURE_BOOKED_SLOTS";
