/**
 * @description home action types
 */
export const REQUEST_USER_REGISTRAION = "REQUEST_USER_REGISTRAION";
export const RECEIVE_USER_REGISTRAION = "RECEIVE_USER_REGISTRAION";
export const FAILURE_USER_REGISTRAION = "FAILURE_USER_REGISTRAION";
export const REQUEST_LIST_OF_USERS = "REQUEST_LIST_OF_USERS";
export const RECEIVE_LIST_OF_USERS = "RECEIVE_LIST_OF_USERS";
export const FAILURE_LIST_OF_USERS = "FAILURE_LIST_OF_USERS";
