/**
 * @description Renter's action types
 */
export const REQUEST_ADD_NEW_ADDRESS = "REQUEST_ADD_NEW_ADDRESS";
export const RECEIVE_ADD_NEW_ADDRESS = "RECEIVE_ADD_NEW_ADDRESS";
export const FAILURE_ADD_NEW_ADDRESS = "FAILURE_ADD_NEW_ADDRESS";
export const REQUEST_ALL_ADDRESSES = "REQUEST_ALL_ADDRESSES";
export const RECEIVE_ALL_ADDRESSES = "RECEIVE_ALL_ADDRESSES";
export const FAILURE_ALL_ADDRESSES = "FAILURE_ALL_ADDRESSES";
export const REQUEST_RENTED_ADDRESSES = "REQUEST_RENTED_ADDRESSES";
export const RECEIVE_RENTED_ADDRESSES = "RECEIVE_RENTED_ADDRESSES";
export const FAILURE_RENTED_ADDRESSES = "FAILURE_RENTED_ADDRESSES";
